# Generated by Django 5.2.5 on 2025-08-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('published_date', models.DateField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('category', models.CharField(default='General', max_length=100)),
                ('is_bestseller', models.BooleanField(default=False)),
            ],
        ),
    ]
