# Generated by Django 5.2.5 on 2025-08-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
